version: "3.8"

services:

  loja-db:
    image: postgres
    container_name: loja-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=produtos
      - PGDATA=/data/postgres

    volumes:
      - ./data/pg:/data/postgres